/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import invoicemaker.client;
import invoicemaker.connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class ClientCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form clientCreatePanel
     */
    public ClientCreatePanel() {
        initComponents();
    }
    
    private boolean isClientExisted(String firstName, String secordName){
        boolean exist = false;
        connection c = new connection();
        try {
            ResultSet r = c.getResult("select * from client where first_name = '" + firstName + "' and secord_name = '" + secordName + "'");
            if(r.next()){
                exist = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClientCreatePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return exist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        clientFirstName = new javax.swing.JLabel();
        clientFirstNameText = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        clientCreateTitle = new javax.swing.JLabel();
        clientFamilyNameText = new javax.swing.JTextField();
        clientFamilyName = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        clientFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientFirstName.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.5;
        add(clientFirstName, gridBagConstraints);

        clientFirstNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        add(clientFirstNameText, gridBagConstraints);

        createButton.setText("ADD");
        createButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.weighty = 1.0;
        add(createButton, gridBagConstraints);

        cancelButton.setText("CANCEL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 0, 0);
        add(cancelButton, gridBagConstraints);

        clientCreateTitle.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        clientCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientCreateTitle.setText("New Client Registration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.weighty = 1.0;
        add(clientCreateTitle, gridBagConstraints);

        clientFamilyNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        add(clientFamilyNameText, gridBagConstraints);

        clientFamilyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientFamilyName.setText("Family Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.5;
        add(clientFamilyName, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        String firstName = clientFirstNameText.getText();
        String secordName = clientFamilyNameText.getText();
        if(firstName.equals("")){
            JOptionPane.showMessageDialog(this, "First Name Cannot Be Empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(secordName.equals("")){
            JOptionPane.showMessageDialog(this, "Family Name Cannot Be Empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(isClientExisted(firstName, secordName)){
            JOptionPane.showMessageDialog(this, "Client Has Already Existed!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(!firstName.equals("") && !secordName.equals("")){
            client c = new client();
            c.setFirstName(firstName);
            c.setSecordName(secordName);
            String sql = "insert into client (first_name, secord_name) values ('" + firstName + "','" + secordName +"')";
            connection conn = new connection();
            conn.excute(sql);
            clientFirstNameText.setText("");
            clientFamilyNameText.setText("");
            JOptionPane.showMessageDialog(this, "New Client " + secordName + " " + firstName + " Has Been Added.", "Sucessful", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel clientCreateTitle;
    private javax.swing.JLabel clientFamilyName;
    private javax.swing.JTextField clientFamilyNameText;
    private javax.swing.JLabel clientFirstName;
    private javax.swing.JTextField clientFirstNameText;
    private javax.swing.JButton createButton;
    // End of variables declaration//GEN-END:variables
}
