/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import invoicemaker.company;
import invoicemaker.connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author root
 */
public class CompanyInfoPanel extends javax.swing.JPanel {
    
    private company company;

    /**
     * Creates new form CompanyInfoPanel
     */
    public CompanyInfoPanel() {
        initComponents();
        company = getCompanyInfo();
        if(company != null){
            fill(company);
        }
    }
    
    private company getCompanyInfo(){
        company c = null;
        try {
            connection con = new connection();
            ResultSet r = con.getResult("select * from company");
            if(r.next()){
                c = new company();
                c.setName(r.getString("company_name"));
                c.setAddress(r.getString("address"));
                c.setPost(r.getString("post_address"));
                c.setPhone(r.getString("phone"));
                c.setEmail(r.getString("email"));
                c.setGst(r.getString("gst"));
                c.setAccountName(r.getString("account_name"));
                c.setAccountNo(r.getString("account_number"));
                c.setBankName(r.getString("bank"));
                c.setSwiftCode(r.getString("swift_code"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CompanyInfoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return c;
    }
    
    private void fill(company c){
        if(c != null){
            companyNameText.setText(c.getName());
            companyAddressText.setText(c.getAddress());
            companyPostText.setText(c.getPost());
            companyPhoneText.setText(c.getPhone());
            companyEmailText.setText(c.getEmail());
            companyGstText.setText(c.getGst());
            companyBankNameText.setText(c.getBankName());
            companyAccountNameText.setText(c.getAccountName());
            companyAccountNoText.setText(c.getAccountNo());
            companySwiftCodeText.setText(c.getSwiftCode());
        }
    }
    
    private boolean checkValueValid(JTextField text, JLabel label){
        if(text.getText().equals("")){
            JOptionPane.showMessageDialog(this, "The " + label.getText()  +" cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        companyDetailTitle = new javax.swing.JLabel();
        companyNameLabel = new javax.swing.JLabel();
        companyNameText = new javax.swing.JTextField();
        companyAddressLabel = new javax.swing.JLabel();
        companyAddressText = new javax.swing.JTextField();
        companyPostLabel = new javax.swing.JLabel();
        companyPostText = new javax.swing.JTextField();
        companyPhoneLabel = new javax.swing.JLabel();
        companyPhoneText = new javax.swing.JTextField();
        companyGstLabel = new javax.swing.JLabel();
        companyGstText = new javax.swing.JTextField();
        companyEmailLabel = new javax.swing.JLabel();
        companyEmailText = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        companyAccountNameLabel = new javax.swing.JLabel();
        companyAccountNameText = new javax.swing.JTextField();
        companyAccountNoLabel = new javax.swing.JLabel();
        companyAccountNoText = new javax.swing.JTextField();
        companyBankLabel = new javax.swing.JLabel();
        companyBankNameText = new javax.swing.JTextField();
        companySwiftCodeLabel = new javax.swing.JLabel();
        companySwiftCodeText = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        companyDetailTitle.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        companyDetailTitle.setText("Company Detail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weighty = 2.5;
        add(companyDetailTitle, gridBagConstraints);

        companyNameLabel.setText("Company Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(companyNameLabel, gridBagConstraints);

        companyNameText.setMinimumSize(new java.awt.Dimension(10, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyNameText, gridBagConstraints);
        companyNameText.getAccessibleContext().setAccessibleDescription("");

        companyAddressLabel.setText("Company Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(companyAddressLabel, gridBagConstraints);

        companyAddressText.setMinimumSize(new java.awt.Dimension(10, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyAddressText, gridBagConstraints);

        companyPostLabel.setText("Company Post");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(companyPostLabel, gridBagConstraints);

        companyPostText.setMinimumSize(new java.awt.Dimension(10, 150));
        companyPostText.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyPostText, gridBagConstraints);

        companyPhoneLabel.setText("Company Phone No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        add(companyPhoneLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyPhoneText, gridBagConstraints);

        companyGstLabel.setText("Company GST No. ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        add(companyGstLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyGstText, gridBagConstraints);

        companyEmailLabel.setText("Company E-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        add(companyEmailLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyEmailText, gridBagConstraints);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.weighty = 2.5;
        add(editButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 50;
        add(cancelButton, gridBagConstraints);

        companyAccountNameLabel.setText("Company Bank Account Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        add(companyAccountNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyAccountNameText, gridBagConstraints);

        companyAccountNoLabel.setText("Company Bank Account No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        add(companyAccountNoLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyAccountNoText, gridBagConstraints);

        companyBankLabel.setText("Company Bank Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        add(companyBankLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companyBankNameText, gridBagConstraints);

        companySwiftCodeLabel.setText("Swift Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        add(companySwiftCodeLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(companySwiftCodeText, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if(checkValueValid(companyNameText, companyNameLabel) && checkValueValid(companyAddressText, companyAddressLabel) &&
                checkValueValid(companyPhoneText, companyPhoneLabel) && checkValueValid(companyPostText, companyPostLabel) &&
                checkValueValid(companyEmailText, companyEmailLabel) && checkValueValid(companyGstText, companyGstLabel) &&
                checkValueValid(companyAccountNameText, companyAccountNameLabel) && checkValueValid(companyAccountNoText, companyAccountNoLabel) &&
                checkValueValid(companyBankNameText, companyBankLabel) && checkValueValid(companySwiftCodeText, companySwiftCodeLabel) && company != null){
            connection con = new connection();
            con.excute("update company set company_name = '" + companyNameText.getText() + "', address = '" + companyAddressText.getText() 
                    + "', post_address = '" + companyPostText.getText() + "', phone = '"+ companyPhoneText.getText() +"', email = '" + companyEmailText.getText() + "', gst = '"
                    + companyGstText.getText() + "', account_name = '" + companyAccountNameText.getText() + "', account_number = '" + companyAccountNoText.getText() + "', bank = '"
                    + companyBankNameText.getText() + "', swift_code = '" + companySwiftCodeText.getText() + "' where id = 1");
        }
        if(company == null){
            connection con = new connection();
            con.excute("insert into company (company_name, address, post_address, phone, email, gst, account_name, account_number, "
                    + "bank, swift_code) values ('" + companyNameText.getText() + "','" + companyAddressText.getText() + "','"  + companyPostText.getText() + "','"
                    + companyPhoneText.getText() +"','" + companyEmailText.getText() + "','"
                    + companyGstText.getText() + "','" + companyAccountNameText.getText() + "','" + companyAccountNoText.getText() + "','"
                    + companyBankNameText.getText() + "', '" + companySwiftCodeText.getText()+ "')");
        }
        getCompanyInfo();
        fill(this.company);
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel companyAccountNameLabel;
    private javax.swing.JTextField companyAccountNameText;
    private javax.swing.JLabel companyAccountNoLabel;
    private javax.swing.JTextField companyAccountNoText;
    private javax.swing.JLabel companyAddressLabel;
    private javax.swing.JTextField companyAddressText;
    private javax.swing.JLabel companyBankLabel;
    private javax.swing.JTextField companyBankNameText;
    private javax.swing.JLabel companyDetailTitle;
    private javax.swing.JLabel companyEmailLabel;
    private javax.swing.JTextField companyEmailText;
    private javax.swing.JLabel companyGstLabel;
    private javax.swing.JTextField companyGstText;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JTextField companyNameText;
    private javax.swing.JLabel companyPhoneLabel;
    private javax.swing.JTextField companyPhoneText;
    private javax.swing.JLabel companyPostLabel;
    private javax.swing.JTextField companyPostText;
    private javax.swing.JLabel companySwiftCodeLabel;
    private javax.swing.JTextField companySwiftCodeText;
    private javax.swing.JButton editButton;
    // End of variables declaration//GEN-END:variables
}
