/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author root
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        createMenu = new javax.swing.JMenu();
        createNewClient = new javax.swing.JMenuItem();
        createNewSchool = new javax.swing.JMenuItem();
        createNewClientRecord = new javax.swing.JMenuItem();
        createNewSchoolRecord = new javax.swing.JMenuItem();
        searchMenu = new javax.swing.JMenu();
        searchInvoice = new javax.swing.JMenuItem();
        settingMenu = new javax.swing.JMenu();
        companyDetail = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVOICE MAKER");
        setMinimumSize(new java.awt.Dimension(800, 600));

        createMenu.setText("Create");

        createNewClient.setText("Create New Personal Client");
        createNewClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createNewClientMousePressed(evt);
            }
        });
        createMenu.add(createNewClient);

        createNewSchool.setText("Create New School Client");
        createNewSchool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createNewSchoolMousePressed(evt);
            }
        });
        createMenu.add(createNewSchool);

        createNewClientRecord.setText("Create New Personal Client Invoice");
        createNewClientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewClientRecordActionPerformed(evt);
            }
        });
        createMenu.add(createNewClientRecord);

        createNewSchoolRecord.setText("Create New School Client Invoice");
        createNewSchoolRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createNewSchoolRecordMousePressed(evt);
            }
        });
        createMenu.add(createNewSchoolRecord);

        menuBar.add(createMenu);

        searchMenu.setText("Search");

        searchInvoice.setText("Search Invoice");
        searchInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInvoiceActionPerformed(evt);
            }
        });
        searchMenu.add(searchInvoice);

        menuBar.add(searchMenu);

        settingMenu.setText("Settings");

        companyDetail.setText("Company Information");
        companyDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                companyDetailMousePressed(evt);
            }
        });
        settingMenu.add(companyDetail);

        menuBar.add(settingMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewClientMousePressed
        // TODO add your handling code here:
        ClientCreatePanel clientPanel = new ClientCreatePanel();
        this.setContentPane(clientPanel);
        this.revalidate();
        //this.repaint();
    }//GEN-LAST:event_createNewClientMousePressed

    private void createNewSchoolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewSchoolMousePressed
        // TODO add your handling code here:
        SchoolCreatePanel schoolPanel = new SchoolCreatePanel();
        this.setContentPane(schoolPanel);
        this.revalidate();
        //this.repaint();
    }//GEN-LAST:event_createNewSchoolMousePressed

    private void createNewSchoolRecordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewSchoolRecordMousePressed
        // TODO add your handling code here:
        SchoolInvoicePanel schoolInvoicePanel = new SchoolInvoicePanel();
        this.setContentPane(schoolInvoicePanel);
        this.revalidate();
        //this.repaint();
    }//GEN-LAST:event_createNewSchoolRecordMousePressed

    private void companyDetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyDetailMousePressed
        // TODO add your handling code here:
        //this.setContentPane(null);
        CompanyInfoPanel companyInfoPanel = new CompanyInfoPanel();
        this.setContentPane(companyInfoPanel);
        this.revalidate();
        //this.repaint();
    }//GEN-LAST:event_companyDetailMousePressed

    private void createNewClientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewClientRecordActionPerformed
        // TODO add your handling code here:
        ClientInovicePanel clientInovicePanel = new ClientInovicePanel();
        this.setContentPane(clientInovicePanel);
        this.revalidate();
    }//GEN-LAST:event_createNewClientRecordActionPerformed

    private void searchInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInvoiceActionPerformed
        // TODO add your handling code here:
        SearchPanel searchPanel = new SearchPanel();
        this.setContentPane(searchPanel);
        this.revalidate();
    }//GEN-LAST:event_searchInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem companyDetail;
    private javax.swing.JMenu createMenu;
    private javax.swing.JMenuItem createNewClient;
    private javax.swing.JMenuItem createNewClientRecord;
    private javax.swing.JMenuItem createNewSchool;
    private javax.swing.JMenuItem createNewSchoolRecord;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem searchInvoice;
    private javax.swing.JMenu searchMenu;
    private javax.swing.JMenu settingMenu;
    // End of variables declaration//GEN-END:variables
}
