/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import invoicemaker.connection;
import invoicemaker.school;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class SchoolCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form schoolCreatePanel
     */
    public SchoolCreatePanel() {
        initComponents();
    }
    
    private boolean isClientExisted(String name){
        boolean exist = false;
        connection c = new connection();
        try {
            ResultSet r = c.getResult("select * from school where school_name = '" + name +  "'");
            if(r.next()){
                exist = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClientCreatePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return exist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        schoolName = new javax.swing.JLabel();
        schoolNameText = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        schoolCreateTitle = new javax.swing.JLabel();
        schoolName1 = new javax.swing.JLabel();
        schoolAddress = new javax.swing.JTextField();
        schoolName2 = new javax.swing.JLabel();
        schoolPhone = new javax.swing.JTextField();
        schoolName3 = new javax.swing.JLabel();
        schoolShortName = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        schoolName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schoolName.setText("School Name : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.1;
        add(schoolName, gridBagConstraints);

        schoolNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.weighty = 0.1;
        add(schoolNameText, gridBagConstraints);

        createButton.setText("ADD");
        createButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.weighty = 1.0;
        add(createButton, gridBagConstraints);

        cancelButton.setText("CANCEL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.weighty = 1.0;
        add(cancelButton, gridBagConstraints);

        schoolCreateTitle.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        schoolCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schoolCreateTitle.setText("New School Registration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(schoolCreateTitle, gridBagConstraints);

        schoolName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schoolName1.setText("Address : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.1;
        add(schoolName1, gridBagConstraints);

        schoolAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.weighty = 0.1;
        add(schoolAddress, gridBagConstraints);

        schoolName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schoolName2.setText("Phone No. : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.1;
        add(schoolName2, gridBagConstraints);

        schoolPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.weighty = 0.1;
        add(schoolPhone, gridBagConstraints);

        schoolName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schoolName3.setText("School Short Name : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.1;
        add(schoolName3, gridBagConstraints);

        schoolShortName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.weighty = 0.1;
        add(schoolShortName, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        String name = schoolNameText.getText();
        String shortName = schoolShortName.getText();
        String address = schoolAddress.getText();
        String phone = schoolPhone.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "School Name Cannot Be Empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(shortName.equals("")){
            JOptionPane.showMessageDialog(this, "School Short Name Cannot Be Empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(this, "School Address Cannot Be Empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(phone.equals("")){
            JOptionPane.showMessageDialog(this, "School Phone Number Cannot Be Empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(isClientExisted(name)){
            JOptionPane.showMessageDialog(this, "School Client Has Already Existed!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(!name.equals("") && !shortName.equals("") && !address.equals("") && !phone.equals("")){
            school s = new school();
            s.setName(name);
            s.setShortName(shortName);
            s.setAddress(address);
            s.setPhone(phone);
            String sql = "insert into school (school_name, shcool_short_name, address, phone) values ('" + name + "','" + shortName + "','" + address + "','" + phone +"')";
            connection conn = new connection();
            conn.excute(sql);
            schoolNameText.setText("");
            schoolShortName.setText("");
            schoolAddress.setText("");
            schoolPhone.setText("");
            JOptionPane.showMessageDialog(this, "New School Client " + name + " Has Been Added.", "Sucessful", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField schoolAddress;
    private javax.swing.JLabel schoolCreateTitle;
    private javax.swing.JLabel schoolName;
    private javax.swing.JLabel schoolName1;
    private javax.swing.JLabel schoolName2;
    private javax.swing.JLabel schoolName3;
    private javax.swing.JTextField schoolNameText;
    private javax.swing.JTextField schoolPhone;
    private javax.swing.JTextField schoolShortName;
    // End of variables declaration//GEN-END:variables
}
